version: '3.4'

services:
  managementdb:
    container_name: managementdb
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - mongo_data:/data/db

  acquisitiondb:
    container_name: acquisitiondb
    restart: always
    ports:
     - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
     - "8080:8000"
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data

  management.api:
    container_name: management.api
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "DatabaseSettings:ConnectionString=mongodb://managementdb:27017"
    depends_on:
     - managementdb
    ports:
      - "8000:80"

  acquisition.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=acquisitiondb:6379"
    depends_on:
     - acquisitiondb
    ports:
      - "8001:80"

